---
title: "section8ArmirKaçabeti.r"
author: "Armir Kaçabeti"
date: "21 Şubat 2018"
output: html_document
---

#8. Using Textual and Binary Formats for Storing Data

#8.1 Using dput() and dump()
```{r}
## Create a data frame
y <- data.frame(a = 1, b = "a")
## Print 'dput' output to console
dput(y)
structure(list(a = 1, b = structure(1L, .Label = "a", class = "factor")), .Names = c("a",
"b"), row.names = c(NA, -1L), class = "data.frame")
```

```{r}
## Send 'dput' output to a file
dput(y, file = "y.R")
## Read in 'dput' output from a file
new.y <- dget("y.R")
new.y
```

```{r}
x <- "foo"
y <- data.frame(a = 1L, b = "a")
```

```{r}
dump(c("x", "y"), file = "data.R")
rm(x, y)
```

```{r}
source("data.R")
str(y)
x
```

#8.2 Binary Formats
```{r}
a <- data.frame(x = rnorm(100), y = runif(100))
b <- c(3, 4.4, 1 / 3)

## Save 'a' and 'b' to a file
save(a, b, file = "mydata.rda")

## Load 'a' and 'b' into your workspace
load("mydata.rda")

```

```{r}
## Save everything to a file
save.image(file = "mydata.RData")

## load all objects in this file
load("mydata.RData")
```

```{r}
x <- list(1, 2, 3)
serialize(x, NULL)
```



